version: '3.8'

services:
  order-service:
    build: 
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "3000:3000"

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "3001:3000"

  meal-service:
    build:
      context: ./meal-service
      dockerfile: Dockerfile
    container_name: meal-service
    ports:
      - "3002:3000"

  delivery-service:
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    container_name: delivery-service
    ports:
      - "3003:3000"

  review-service:
    build:
      context: ./review-service
      dockerfile: Dockerfile
    container_name: review-service
    ports:
      - "3004:3000"